'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { parseUserContainersConf, collectProxySettings, renderContainersConf, writePrivateContainersConf } = require('../lib/proxy-config');

let root;
beforeEach(() => { root = fs.mkdtempSync(path.join(os.tmpdir(), 'manyoyo-proxy-')); });
afterEach(() => fs.rmSync(root, { recursive: true, force: true }));

describe('parseUserContainersConf', () => {
    test('takes only proxy entries from [engine] env, in single- or multi-line arrays', () => {
        const parsed = parseUserContainersConf(`
[engine]
cgroup_manager = "systemd"
env = [
  "HTTP_PROXY=http://127.0.0.1:7890",
  "https_proxy=http://127.0.0.1:7890",
  "NO_PROXY=localhost,127.0.0.1",
  "SECRET_TOKEN=abc",
  "PATH=/evil"
]
[network]
network_backend = "netavark"
`);
        expect(parsed.env).toEqual({
            http_proxy: 'http://127.0.0.1:7890',
            https_proxy: 'http://127.0.0.1:7890',
            no_proxy: 'localhost,127.0.0.1'
        });
    });

    test('handles IPv6 proxy addresses whose brackets sit inside the quoted strings', () => {
        expect(parseUserContainersConf('[engine]\nenv = ["http_proxy=http://[::1]:7890", "no_proxy=localhost"]\n').env)
            .toEqual({ http_proxy: 'http://[::1]:7890', no_proxy: 'localhost' });
    });

    test('reads the [containers] http_proxy pass-through switch and ignores env under other sections', () => {
        expect(parseUserContainersConf('[containers]\nhttp_proxy = false\n').passToContainers).toBe(false);
        expect(parseUserContainersConf('[containers]\nhttp_proxy = true\n').passToContainers).toBe(true);
        expect(parseUserContainersConf('[containers]\nenv = ["http_proxy=http://x:1"]\n').env).toEqual({});
        expect(parseUserContainersConf('').passToContainers).toBeNull();
    });

    test('drops values that could break out of the generated TOML or the environment', () => {
        const parsed = parseUserContainersConf('[engine]\nenv = ["http_proxy=http://a:1\\"; rm -rf ~", "https_proxy=http://ok:1", "all_proxy=$(id)", "no_proxy=a`b`"]\n');
        expect(parsed.env).toEqual({ https_proxy: 'http://ok:1' });
    });
});

describe('collectProxySettings', () => {
    function userConf(text) {
        fs.mkdirSync(path.join(root, '.config/containers'), { recursive: true });
        fs.writeFileSync(path.join(root, '.config/containers/containers.conf'), text);
    }

    test('uses the user containers.conf first and environment variables to fill gaps', () => {
        userConf('[engine]\nenv = ["http_proxy=http://from-file:1"]\n');
        const settings = collectProxySettings({ homeDir: root, env: { HTTPS_PROXY: 'http://from-env:2', http_proxy: 'http://ignored:3', OTHER: 'x' } });
        expect(settings.env).toEqual({ http_proxy: 'http://from-file:1', https_proxy: 'http://from-env:2' });
    });

    test('no config and no variables means no proxy at all', () => {
        expect(collectProxySettings({ homeDir: root, env: {} })).toEqual({ env: {}, passToContainers: null });
    });
});

describe('writePrivateContainersConf', () => {
    const podmanRoot = () => path.join(root, '.manyoyo/runtime/podman');

    test('writes helper_binaries_dir plus the proxy settings with 0600 permissions', () => {
        fs.mkdirSync(path.join(root, '.config/containers'), { recursive: true });
        fs.writeFileSync(path.join(root, '.config/containers/containers.conf'), '[engine]\nenv = ["http_proxy=http://u:p@127.0.0.1:7890"]\n[containers]\nhttp_proxy = true\n');
        const result = writePrivateContainersConf({ podmanRoot: podmanRoot(), homeDir: root, env: {} });
        expect(result).toEqual(expect.objectContaining({ written: true, proxyNames: ['http_proxy'] }));
        const text = fs.readFileSync(path.join(podmanRoot(), 'containers.conf'), 'utf8');
        expect(text.startsWith('# generated by manyoyo installer\n[engine]\n')).toBe(true);
        expect(text).toContain(`helper_binaries_dir = [${JSON.stringify(path.join(podmanRoot(), 'bin'))}]`);
        expect(text).toContain('env = ["http_proxy=http://u:p@127.0.0.1:7890"]');
        expect(text).toContain('[containers]\nhttp_proxy = true');
        expect(fs.statSync(path.join(podmanRoot(), 'containers.conf')).mode & 0o777).toBe(0o600);
    });

    test('without any proxy the file is just helper_binaries_dir', () => {
        writePrivateContainersConf({ podmanRoot: podmanRoot(), homeDir: root, env: {} });
        const text = fs.readFileSync(path.join(podmanRoot(), 'containers.conf'), 'utf8');
        expect(text).not.toContain('env =');
        expect(text).not.toContain('[containers]');
    });

    test('regenerates its own file (the proxy may have changed) and upgrades the minimal config from container-runtime', () => {
        fs.mkdirSync(podmanRoot(), { recursive: true });
        fs.writeFileSync(path.join(podmanRoot(), 'containers.conf'), '[engine]\nhelper_binaries_dir = ["/x/bin"]\n');
        expect(writePrivateContainersConf({ podmanRoot: podmanRoot(), homeDir: root, env: { http_proxy: 'http://a:1' } }).written).toBe(true);
        expect(writePrivateContainersConf({ podmanRoot: podmanRoot(), homeDir: root, env: { http_proxy: 'http://b:2' } }).written).toBe(true);
        expect(fs.readFileSync(path.join(podmanRoot(), 'containers.conf'), 'utf8')).toContain('http_proxy=http://b:2');
    });

    test('never overwrites a file the user edited by hand', () => {
        fs.mkdirSync(podmanRoot(), { recursive: true });
        fs.writeFileSync(path.join(podmanRoot(), 'containers.conf'), '[engine]\nhelper_binaries_dir = ["/x/bin"]\nruntime = "crun"\n');
        const result = writePrivateContainersConf({ podmanRoot: podmanRoot(), homeDir: root, env: { http_proxy: 'http://a:1' } });
        expect(result).toEqual(expect.objectContaining({ written: false, reason: 'user-modified' }));
        expect(fs.readFileSync(path.join(podmanRoot(), 'containers.conf'), 'utf8')).toContain('runtime = "crun"');
    });

    test('render is deterministic', () => {
        expect(renderContainersConf({ podmanRoot: '/p', proxy: { env: { http_proxy: 'http://a:1' }, passToContainers: false } }))
            .toBe('[engine]\nhelper_binaries_dir = ["/p/bin"]\nenv = ["http_proxy=http://a:1"]\n\n[containers]\nhttp_proxy = false\n');
    });
});
