'use strict';

// 私有 Podman 设了 CONTAINERS_CONF，不会再读用户自己的 ~/.config/containers/containers.conf，
// 所以安装时把其中“有用的”代理设置抄过来：只抄代理相关项，其它（仓库、存储路径等）一概不碰。
// 用法（安装器调用）：node proxy-config.js --write-conf <私有podman目录> <用户HOME>

const fs = require('fs');
const os = require('os');
const path = require('path');

const PROXY_NAMES = ['http_proxy', 'https_proxy', 'no_proxy', 'all_proxy'];

function isSafeValue(value) {
    // 会写进 TOML 字符串，也可能进命令环境：拒绝换行、引号、反斜杠与控制字符
    return typeof value === 'string' && value.length > 0 && value.length < 2048 && !/[\r\n\0"'\\`$]/.test(value);
}

function sectionBody(text, name) {
    const lines = text.split('\n');
    let current = '';
    const body = [];
    for (const line of lines) {
        const header = line.match(/^\s*\[([^\]]+)\]\s*$/);
        if (header) { current = header[1].trim(); continue; }
        if (current === name) body.push(line);
    }
    return body.join('\n');
}

/**
 * 从用户的 containers.conf 文本里取出代理环境变量（[engine] env = [...]，可多行）与 [containers] http_proxy 开关。
 * @returns {{env: Object<string,string>, passToContainers: boolean|null}}
 */
function parseUserContainersConf(text) {
    const result = { env: {}, passToContainers: null, dropped: [] };
    const engine = sectionBody(String(text || ''), 'engine');
    // 数组里的字符串可能含 ]（如 IPv6 代理 http://[::1]:7890），所以按“引号串 或 非 ] 字符”匹配
    const envMatch = engine.match(/^\s*env\s*=\s*\[((?:"(?:[^"\\\n]|\\.)*"|[^\]"])*)\]/m);
    if (envMatch) {
        for (const entry of envMatch[1].matchAll(/"((?:[^"\\\n]|\\.)*)"/g)) {
            const index = entry[1].indexOf('=');
            if (index <= 0) continue;
            const name = entry[1].slice(0, index).trim().toLowerCase();
            const value = entry[1].slice(index + 1).trim();
            if (!PROXY_NAMES.includes(name)) continue;
            if (isSafeValue(value)) result.env[name] = value;
            else if (value) result.dropped.push(name);
        }
    }
    const containers = sectionBody(String(text || ''), 'containers');
    const flag = containers.match(/^\s*http_proxy\s*=\s*(true|false)\s*$/m);
    if (flag) result.passToContainers = flag[1] === 'true';
    return result;
}

function proxyFromEnvironment(env, dropped = []) {
    const found = {};
    for (const name of PROXY_NAMES) {
        const value = env[name] || env[name.toUpperCase()];
        if (isSafeValue(value)) found[name] = value;
        else if (value) dropped.push(name);
    }
    return found;
}

/**
 * 汇总代理：用户的 containers.conf 优先（那是对 Podman 实际生效的配置），环境变量补缺。
 */
function collectProxySettings({ homeDir = os.homedir(), env = process.env, readFile = file => fs.readFileSync(file, 'utf8') } = {}) {
    let fromFile = { env: {}, passToContainers: null };
    const userConf = path.join(homeDir, '.config', 'containers', 'containers.conf');
    try {
        fromFile = parseUserContainersConf(readFile(userConf));
    } catch (error) {
        // 没有用户配置很正常
    }
    const dropped = [];
    const fromEnv = proxyFromEnvironment(env, dropped);
    const merged = { ...fromEnv, ...fromFile.env };
    // 被丢弃的项只有在最终没有可用值时才算“丢了”（只报名字，不打印值：可能带密码）
    return {
        env: merged,
        passToContainers: fromFile.passToContainers,
        dropped: [...new Set([...dropped, ...(fromFile.dropped || [])])].filter(name => !(name in merged))
    };
}

function renderContainersConf({ podmanRoot, proxy }) {
    const lines = ['[engine]', `helper_binaries_dir = [${JSON.stringify(path.join(podmanRoot, 'bin'))}]`];
    const entries = Object.entries(proxy.env).map(([name, value]) => JSON.stringify(`${name}=${value}`));
    if (entries.length > 0) lines.push(`env = [${entries.join(', ')}]`);
    if (proxy.passToContainers !== null) lines.push('', '[containers]', `http_proxy = ${proxy.passToContainers}`);
    return `${lines.join('\n')}\n`;
}

/**
 * 写 <podmanRoot>/containers.conf。每次安装都重新生成（代理会变），
 * 但只覆盖带本工具标记的文件，用户手改过的不动。
 */
function writePrivateContainersConf({ podmanRoot, homeDir, env = process.env }) {
    const target = path.join(podmanRoot, 'containers.conf');
    const marker = '# generated by manyoyo installer';
    if (fs.existsSync(target) && !fs.readFileSync(target, 'utf8').startsWith(marker)) {
        const legacy = fs.readFileSync(target, 'utf8');
        // lib/container-runtime.js 首次选择时写的最小配置（只有 helper_binaries_dir）可以安全升级
        if (/^\[engine\]\nhelper_binaries_dir = \[[^\n]*\]\n$/.test(legacy) === false) {
            return { path: target, written: false, reason: 'user-modified' };
        }
    }
    const proxy = collectProxySettings({ homeDir, env });
    fs.mkdirSync(podmanRoot, { recursive: true });
    // 代理 URL 里可能带账号密码，和用户自己的 containers.conf 一样只给本人读写
    fs.writeFileSync(target, `${marker}\n${renderContainersConf({ podmanRoot, proxy })}`, { mode: 0o600 });
    fs.chmodSync(target, 0o600);
    return { path: target, written: true, proxyNames: Object.keys(proxy.env), passToContainers: proxy.passToContainers, droppedNames: proxy.dropped };
}

module.exports = {
    parseUserContainersConf,
    collectProxySettings,
    renderContainersConf,
    writePrivateContainersConf
};

if (require.main === module) {
    const [flag, podmanRoot, homeDir] = process.argv.slice(2);
    if (flag !== '--write-conf' || !podmanRoot) {
        console.error('用法: node proxy-config.js --write-conf <私有podman目录> [用户HOME]');
        process.exit(2);
    }
    const result = writePrivateContainersConf({ podmanRoot, homeDir: homeDir || os.homedir() });
    console.log(result.written
        ? `已生成 ${result.path}（代理项: ${result.proxyNames.join(', ') || '无'}）`
        : `保留用户修改过的 ${result.path}`);
    if (result.droppedNames && result.droppedNames.length > 0) {
        console.log(`注意：以下代理项含引号、反斜杠、$ 或反引号等不安全字符，没有抄进私有 Podman 配置: ${result.droppedNames.join(', ')}（需要的话请手动编辑 ${result.path}）`);
    }
}
